-- Publishes photo updates: builds thumbnails + posts.json, then commits and
-- pushes ONLY the photo-related files. Runs silently and reports the result in
-- a single dialog. No Terminal window.
--
-- Staged paths include photo/ (per-photo share pages), sitemap.xml, and
-- avatars/ — all regenerated by build.py and all part of a photo update.
-- If a previous run committed but failed to push (e.g. expired GitHub
-- sign-in), the next run detects the un-pushed commit and pushes it.

set shellCmd to "export PATH=/opt/homebrew/bin:/usr/bin:/bin; cd /Users/kev/Claude/photography-portfolio && python3 build.py && git add photos thumbs previews other-photos thumbs-other previews-other posts.json photo sitemap.xml avatars && { git diff --cached --quiet || git commit -m \"Update photos ($(date '+%Y-%m-%d %H:%M'))\"; } && { if [ \"$(git rev-list --count @{u}..HEAD 2>/dev/null || echo 0)\" -gt 0 ]; then git push && echo PUBLISHED; else echo NOCHANGES; fi; }"

try
	set shellOut to do shell script shellCmd
	if shellOut contains "NOCHANGES" then
		display dialog "No new photo changes to publish." & return & "Add photos and captions first, then run this again." buttons {"OK"} default button "OK" with title "Publish"
	else
		display dialog "Published!" & return & return & "The site updates in about a minute at aspy.pics." buttons {"OK"} default button "OK" with title "Publish"
	end if
on error errMsg
	if errMsg contains "could not read Username" or errMsg contains "Authentication failed" or errMsg contains "Device not configured" then
		display dialog "Publish failed: GitHub sign-in needed." & return & return & "Your commit was saved locally but couldn't be pushed. Sign in to GitHub once (run 'gh auth login', or push from the Terminal so macOS stores your token), then run Publish again — it will push the saved commit." buttons {"OK"} default button "OK" with title "Publish" with icon caution
	else
		display dialog "Publish failed:" & return & return & errMsg buttons {"OK"} default button "OK" with title "Publish" with icon caution
	end if
end try
